name: fast_barcode_scanner
description: A fast barcode scanner using MLKit on Android and AVFoundation on iOS.
version: 2.0.0-dev.2
homepage: https://github.com/jhoogstraat/fast_barcode_scanner
publish_to: none
repository: https://github.com/jhoogstraat/fast_barcode_scanner

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  fast_barcode_scanner_platform_interface:
    url: git://github.com/saulurquiagaftf/fast_barcode_scanner.git
    ref: 20_rectangle_of_interest
    path: fast_barcode_scanner_platform_interface/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.jhoogstraat.fast_barcode_scanner
        pluginClass: FastBarcodeScannerPlugin
      ios:
        pluginClass: FastBarcodeScannerPlugin
